version: '2' # specify docker-compose version
# Define the services/containers to be run
services:
  angular: # name of the first service
    hostname: localhost
    build: angular-app # specify the directory of the Dockerfile
    ports:
      - "8080:80" # specify port forewarding

  express: #name of the second service
    build: express-service # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forewarding
    links:
      - database

  database: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forewarding
    volumes:
      - mongo_data:/data/db
volumes:
   mongo_data:

